# Generated by Django 4.2.16 on 2024-12-09 15:53

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=250, verbose_name="Title")),
                ("slug", models.SlugField(unique=True)),
                ("body", models.TextField(verbose_name="Post")),
                (
                    "banner_image",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Banner Image",
                    ),
                ),
                (
                    "upvotes",
                    models.PositiveIntegerField(default=0, verbose_name="Upvotes"),
                ),
                (
                    "downvotes",
                    models.PositiveIntegerField(default=0, verbose_name="Downvotes"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "bookmarked_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="bookmarked_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "downvoted_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="downvoted_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "upvoted_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="upvoted_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="Image"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Image",
                "verbose_name_plural": "Posts Images",
            },
        ),
    ]
